services:
  - type: web
    name: literature-review-visualizer
    env: python
    plan: free
    buildCommand: pip install -r requirements_lit_review_visualizer.txt && npm install && npm run build
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
    healthCheckPath: /
